### ISSUE TITLE
Sample App doesn't run

### ISSUE THREAD

**Issue by mortensen** [DNSBelgium/rdap-server-sample-gtld#2]
The maven pom references a server version 2.0.0-SNAPSHOT, which isn't uploaded anywhere. mvn clean install doesn't work out of the box though. Is this project as well as the server still maintaned?

**Comment by darkmanneke** [comment]
You can build and run the sample project if you first build and install the server.

Clone the server and run "./gradlew clean build install". This will add the server version 2.0.0-SNAPSHOT in your local mvn repo. After that you can build the sample project.

The server is maintained. The sample project too, but with some delay.
Note that only the help query of the sample is working. The old implementation that was using public whois to create rdap responses no longer works.

**Comment by mortensen** [comment]
Ok this helped. Thank you.
